### ISSUE TITLE
Rewrite discards expression for variable

### ISSUE THREAD

**Issue by dwijnand** [google/rerast#23]
Given:

```rust
pub struct Execs {
    expect_exit_code: Option<i32>,
}

impl Execs {
    /// Verify the exit code from the process.
    pub fn with_status(mut self, expected: i32) -> Execs {
        self.expect_exit_code = Some(expected);
        self
    }
}

pub fn execs() -> Execs {
    Execs {
        expect_exit_code: Some(0),
    }
}

pub fn usage() {
    execs().with_status(0);
}
```

(derived from Cargo's testsuite support code)

The rewrite rule:

```rust
use Execs;

fn rule1(e: Execs) {
   replace!(e.with_status(0) => e);
}
```

applied with:

```terminal
cargo +nightly rerast --rules_file=rewrite.rs --force
```

results in:

```rust
 pub fn usage() {
-    execs().with_status(0);
+    e;
 }
```

which doesn't compile. It should result in:

```rust
 pub fn usage() {
-    execs().with_status(0);
+    execs();
 }
```

**Comment by davidlattimore** [comment]
Thanks for the report. I was surprised I didn't have a test for that. Turned out I had a test for the entire LHS being a placeholder, but not one for the entire RHS. Then when I was processing the replacement expression, I was only checking the sub-expressions of the replacement pattern for placeholders, not the replacement pattern itself.

Fix is now pushed to crates.io.

**Comment by dwijnand** [comment]
I see! Thanks for the fix.
