### ISSUE TITLE
Build fails on 1.35-nightly

### ISSUE THREAD

**Issue by nerdrew** [google/rerast#27]
```
% rustc --version
rustc 1.35.0-nightly (94fd04589 2019-03-21)
% cargo install rerast
...
error[E0599]: no variant named `Ctor` found for type `rustc::hir::def::Def` in the current scope
   --> /Users/lazarus/.cargo/registry/src/github.com-1ecc6299db9ec823/rerast-0.1.46/src/change_to_rule.rs:572:20
    |
572 |             | Def::Ctor(..) => {
    |               -----^^^^---- variant not found in `rustc::hir::def::Def`
```

**Comment by davidlattimore** [comment]
Hi,

Thanks for reporting that. Good to see people using Rerast. Rerast needs updating pretty often due to changes in the compiler's internal APIs. The last such update was https://github.com/google/rerast/commit/d6c2fc406b51f3df1718af7b8c0e2824663f710d where I updated it to work with version 2019-03-25 of the compiler. I'd suggest updating to the latest nightly and trying again. If you want to stick with the version you've got, you can likely install the previous version of rerast which I think should work with the version you've got. I think this would be something like
cargo +nightly install --version 0.1.45 rerast
Hope that helps

**Comment by nerdrew** [comment]
LOL. Sorry about the noise then. The nightly builds have broken `rls` and `clippy` (has been broken for a week+), so rustup wasn't installing them for me. I installed the old version, and it worked. THANKS!
