### ISSUE TITLE
dot async example

### ISSUE THREAD

**Issue by elbaro** [google/rerast#28]
Is it possible to replace await macros to dot await syntax?

```rs
fn rule1<T>(r: T) {
  replace!(await!(r) => r.await)
}
```

```
Processing src/main.rs
error[E0728]: `await` is only allowed inside `async` functions and blocks
 --> src/__rerast_rules.rs:3:12
  |
2 | fn rule1<T>(r: T) {
  |    ----- this is not `async`
3 |   replace!(await!(r) => r.await)
  |            ^^^^^^^^^ only allowed inside `async` functions and blocks

error[E0728]: `await` is only allowed inside `async` functions and blocks
 --> src/__rerast_rules.rs:3:25
  |
2 | fn rule1<T>(r: T) {
  |    ----- this is not `async`
3 |   replace!(await!(r) => r.await)
  |                         ^^^^^^^ only allowed inside `async` functions and blocks

error: aborting due to 2 previous errors

```

**Comment by davidlattimore** [comment]
Good question. I just had a bit of a look... first to fix the error above, the function rule1 needs to be declared async. Then you hit an error that the std::future::Future isn't implemented for T. The following rule then compiles without error:

async fn rule1<T: std::future::Future>(r: T) {
  replace!(await!(r) => r.await)
}

... however it still doesn't match. I had look at why. It seems that the await! macro expands to code like the following:

{
    let mut pinned = a();
    loop  {
        match ::std::future::poll_with_tls_context(unsafe {
                                                       <::std::pin::Pin>::new_unchecked(&mut pinned)
                                                   }) {
            ::std::task::Poll::Ready(result) => break result ,
            ::std::task::Poll::Pending => { }
        }
        yield ();
    }
}

Rerast is failing to match &mut pinned in the rule to &mut pinned in the code because the two pinned variables are different variables. I think that could probably in theory be fixed. Names like 'pinned' in the expanded code should probably be treated a bit like placeholders. I'll give it some more thought.

**Comment by davidlattimore** [comment]
With release 0.1.52, this should now work using a rule like:
```
async fn rule1<T: std::future::Future>(r: T) {
  replace!(await!(r) => r.await)
}
```
